apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-app-svc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-app-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-app-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: devops-app-svc
  namespace: default
roleRef:
  kind: Role
  name: devops-app-role
  apiGroup: rbac.authorization.k8s.io
