# Give Access to K8 user vino to persistent volume and PVC in all namespaces - Cluster scope resource

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-app-cluster-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-app-rolebinding
  namespace: default
subjects:
- kind: User
  name: kubeusr
  namespace: default
roleRef:
  kind: ClusterRole
  name: devops-app-cluster-role
  apiGroup: rbac.authorization.k8s.io
